# Generated by Django 3.2.16 on 2022-12-01 02:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_id', models.CharField(max_length=128, unique=True)),
                ('price', models.IntegerField()),
                ('daily_highest_price', models.IntegerField(default=0)),
                ('daily_lowest_price', models.IntegerField(default=0)),
                ('hourly_highest_price', models.IntegerField(default=0)),
                ('hourly_lowest_price', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=32, unique=True)),
                ('availability', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
