version: '3.5'

services:
    vernemq:
        environment:
            - DOCKER_VERNEMQ_ACCEPT_EULA=yes
            - DOCKER_VERNEMQ_ALLOW_ANONYMOUS=on
            - MQTT_TOPIC=thndr-trading
        image: erlio/docker-vernemq
        ports:
          - 1883:1883
    streamer:
        environment:
            - MQTT_HOST=vernemq
            - MQTT_PORT=1883
            - MQTT_TOPIC=thndr-trading
        image: thndr/streamer:0.2
        depends_on:
            - vernemq

    migrations:
        build: .
        command: python manage.py migrate
        volumes:
            - .:/django

    app:
        build: .
        volumes:
            - .:/django
        ports:
          - 8000:8000
        image: app:django
        command: python manage.py runserver 0.0.0.0:8000
        depends_on:
            - vernemq
            - streamer
            - migrations
